name = "DiffEqDocs"
uuid = "d91efeb5-c178-44a6-a2ee-51685df7c78e"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "6.16.1"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
DiffEqBase = "6.5"
DiffEqProblemLibrary = "4.5"
Documenter = "0.23, 0.24, 0.25"
